# Generated by Django 3.1.12 on 2024-12-18 02:25

from django.db import migrations, models
import django.db.models.deletion
import functions.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('app_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('short_description', models.TextField()),
                ('header_image', models.URLField()),
                ('capsule_image', models.URLField()),
                ('release_date', models.DateField(null=True)),
                ('quarter', models.CharField(default=None, max_length=10, null=True)),
                ('coming_soon', models.BooleanField(default=False)),
                ('developers', models.CharField(max_length=500)),
                ('publishers', models.CharField(max_length=500)),
                ('tags', functions.fields.MongoSafeJSONField(default=list)),
                ('positive_reviews', models.IntegerField(default=0)),
                ('negative_reviews', models.IntegerField(default=0)),
                ('supported_languages', models.TextField()),
                ('pc_requirements', functions.fields.MongoSafeJSONField(default=list)),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.IntegerField(default=0)),
                ('categories', functions.fields.MongoSafeJSONField(default=list)),
                ('genres', functions.fields.MongoSafeJSONField(default=list)),
                ('screenshots', functions.fields.MongoSafeJSONField(default=list)),
                ('recommendations', functions.fields.MongoSafeJSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(default=None, max_length=100)),
                ('thumbnails', models.URLField()),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('channelImage', models.URLField(default='https://example.com/default-image.jpg')),
                ('channelName', models.CharField(db_index=True, max_length=100)),
                ('publishedAt', models.DateTimeField(db_index=True)),
                ('viewCount', models.BigIntegerField(default=0)),
                ('summary', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube', to='functions.game')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_analysis', models.JSONField(default=list)),
                ('all_analysis', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_analysis', to='functions.game')),
            ],
            options={
                'db_table': 'steam_game_reviewanalysis',
            },
        ),
    ]
